"""
BreadFree Core Data Models

Defines the unified data structures used across backtest and live trading:
- Signal: Strategy output (intent to trade)
- Order: Submitted order with lifecycle management
- Trade: Executed fill record
- Account: Account state snapshot
- PositionInfo: Position state snapshot

Design reference:
- nautilus_trader: Strong-typed models with enums
- vnpy: Event-driven data flow
"""

from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime
from typing import Optional, Dict


# ──────────────────────────────────────────────
# Enums
# ──────────────────────────────────────────────

class Direction(Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OrderStatus(Enum):
    PENDING = "PENDING"           # Created, not yet submitted
    SUBMITTED = "SUBMITTED"       # Sent to broker/gateway
    PARTIAL_FILLED = "PARTIAL"    # Partially filled
    FILLED = "FILLED"             # Fully filled
    CANCELLED = "CANCELLED"       # Cancelled by user or system
    REJECTED = "REJECTED"         # Rejected by broker or risk manager


# ──────────────────────────────────────────────
# Signal: output of strategy, input to OMS
# ──────────────────────────────────────────────

@dataclass
class Signal:
    """
    A trading signal generated by a strategy.
    This is the bridge between strategy logic and order execution.
    """
    symbol: str
    direction: Direction
    quantity: int
    order_type: OrderType = OrderType.MARKET
    price: Optional[float] = None       # Required for LIMIT orders
    reason: str = ""                     # Human-readable reason (useful for LLM audit)
    timestamp: Optional[datetime] = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


# ──────────────────────────────────────────────
# Order: lifecycle-managed order
# ──────────────────────────────────────────────

@dataclass
class Order:
    """
    A submitted order with full lifecycle tracking.
    Created by OrderManager from a Signal.
    """
    order_id: str
    symbol: str
    direction: Direction
    order_type: OrderType
    quantity: int
    price: Optional[float] = None       # Limit price (None for market orders)
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: int = 0
    avg_fill_price: float = 0.0
    commission: float = 0.0
    create_time: Optional[datetime] = None
    update_time: Optional[datetime] = None
    reject_reason: str = ""
    source: str = ""                    # Which strategy generated this order

    def __post_init__(self):
        now = datetime.now()
        if self.create_time is None:
            self.create_time = now
        if self.update_time is None:
            self.update_time = now

    @property
    def is_active(self) -> bool:
        """Whether the order is still active (can be filled or cancelled)."""
        return self.status in (
            OrderStatus.PENDING,
            OrderStatus.SUBMITTED,
            OrderStatus.PARTIAL_FILLED,
        )

    @property
    def remaining_quantity(self) -> int:
        return self.quantity - self.filled_quantity


# ──────────────────────────────────────────────
# Trade: a single fill / execution record
# ──────────────────────────────────────────────

@dataclass
class Trade:
    """
    A single execution (fill) record.
    One Order can produce multiple Trades (partial fills).
    """
    trade_id: str
    order_id: str
    symbol: str
    direction: Direction
    quantity: int
    price: float
    commission: float = 0.0
    timestamp: Optional[datetime] = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()

    @property
    def notional(self) -> float:
        """Total notional value of this fill."""
        return self.quantity * self.price


# ──────────────────────────────────────────────
# Account: account state snapshot
# ──────────────────────────────────────────────

@dataclass
class Account:
    """Account state snapshot."""
    total_equity: float = 0.0
    available_cash: float = 0.0
    frozen_cash: float = 0.0
    position_value: float = 0.0
    total_pnl: float = 0.0
    initial_cash: float = 0.0
    commission_rate: float = 0.0003
    timestamp: Optional[datetime] = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


# ──────────────────────────────────────────────
# PositionInfo: position state snapshot
# ──────────────────────────────────────────────

@dataclass
class PositionInfo:
    """
    A snapshot of a single position.
    Distinct from broker.Position to avoid coupling.
    """
    symbol: str
    quantity: int
    avg_price: float
    market_price: float = 0.0
    market_value: float = 0.0
    unrealized_pnl: float = 0.0

    def update_market_price(self, price: float):
        self.market_price = price
        self.market_value = self.quantity * price
        self.unrealized_pnl = (price - self.avg_price) * self.quantity


# ──────────────────────────────────────────────
# Event: unified event for EventBus
# ──────────────────────────────────────────────

class EventType(Enum):
    BAR = "BAR"                 # New bar data arrived
    SIGNAL = "SIGNAL"           # Strategy generated a signal
    ORDER = "ORDER"             # Order status changed
    TRADE = "TRADE"             # Trade executed
    POSITION = "POSITION"       # Position updated
    ACCOUNT = "ACCOUNT"         # Account updated
    RISK = "RISK"               # Risk alert
    LOG = "LOG"                 # General log event


@dataclass
class Event:
    """Unified event for the EventBus."""
    event_type: EventType
    data: object                # Payload (Signal, Order, Trade, etc.)
    timestamp: Optional[datetime] = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()
